# Generated by Django 4.1.3 on 2023-01-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
    ]
