# Generated by Django 4.1.3 on 2023-01-12 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_cartitems_size_product_size"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="size",),
    ]
