# Generated by Django 4.1.3 on 2023-01-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(to="product.size"),
        ),
    ]
