# Generated by Django 4.1.3 on 2023-03-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_brand_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
