# Generated by Django 4.1.3 on 2023-03-28 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_brand_alter_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
