# Generated by Django 4.1.3 on 2023-04-07 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_category_slug_remove_subcategory_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('name', 'category')},
        ),
    ]
