# Generated by Django 4.1.3 on 2023-04-07 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_subcategory_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('offer', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('start', models.DateTimeField(default=None)),
                ('end', models.DateTimeField(default=None)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
    ]
