# Generated by Django 4.1.3 on 2023-04-12 06:40

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='end',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='start',
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
