# Generated by Django 4.1.3 on 2023-04-15 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0017_remove_coupon_end_remove_coupon_offer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="users_applied",
            field=models.ManyToManyField(
                blank=True, related_name="applied_coupons", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
