# Generated by Django 4.1.3 on 2023-04-15 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0018_coupon_users_applied"),
    ]

    operations = [
        migrations.RemoveField(model_name="coupon", name="users_applied",),
    ]
