# Generated by Django 4.1.3 on 2023-04-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0019_remove_coupon_users_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="is_coupon_applied",
            field=models.BooleanField(default=False),
        ),
    ]
