# Generated by Django 4.1.3 on 2023-04-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0020_cartitems_is_coupon_applied"),
    ]

    operations = [
        migrations.RemoveField(model_name="cartitems", name="is_coupon_applied",),
    ]
