# Generated by Django 4.1.3 on 2023-04-15 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0021_remove_cartitems_is_coupon_applied"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="applied_coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.coupon",
            ),
        ),
    ]
