# Generated by Django 4.1.3 on 2023-04-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0022_cartitems_applied_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="discount",
            field=models.IntegerField(default=0),
        ),
    ]
